# Generated by Django 6.1 on 2026-08-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_cartitem_cart_product_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed", "Fixed")],
                        max_length=20,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
