# Generated by Django 6.1 on 2026-08-10 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_discountmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="payments.discountmodel",
            ),
        ),
    ]
