# Generated by Django 6.1 on 2026-08-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_productprice_currency_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartmodel",
            name="currency",
        ),
    ]
