# Generated by Django 6.1 on 2026-08-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_rename_currencymodel_exchangeratemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitemmodel",
            name="exchange_rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="payments.exchangeratemodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitemmodel",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
            preserve_default=False,
        ),
    ]
