# Generated by Django 6.1 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0012_paymentmodel_currency_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("rate", models.IntegerField()),
            ],
        ),
    ]
