# Generated by Django 6.1 on 2026-08-12 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_taxmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="tax",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="payments.taxmodel",
            ),
        ),
    ]
