# Generated by Django 6.1 on 2026-08-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_ordermodel_tax"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeWebhookEventModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
