name: stripe_test
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DATABASE_DB: ${DATABASE_DB}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - api

  db:
    image: postgres:16-alpine
    container_name: db
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data

  db-test:
    image: postgres:16-alpine
    container_name: db-test
    ports:
      - "5434:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - stripe_test_data:/var/lib/postgresql/data

volumes:
  stripe_test_data:
